### ISSUE TITLE
Publish HandyWinGet-GUI to winget-packages

### ISSUE THREAD

**Issue by saulens22** [HandyOrg/HandyWinGet-GUI#2]
It would be nice if this app could update itself.

**Comment by ghost1372** [comment]
Thanks for the suggestion
I will definitely consider this

**Comment by ghost1372** [comment]
now handywinget is available in winget manifest😁
https://github.com/microsoft/winget-pkgs/tree/master/manifests/HandyOrg/HandyWinGet-GUI
