### ISSUE TITLE
Use MSIX installer

### ISSUE THREAD

**Issue by Poopooracoocoo** [HandyOrg/HandyWinGet-GUI#3]

**Comment by ghost1372** [comment]
Yes, I will try

**Comment by ghost1372** [comment]
Unfortunately, I had a problem with the digital signature and I couldn't put it in the MSIX type anyway, the msi setup was added to winget manifests
https://github.com/microsoft/winget-pkgs/tree/master/manifests/HandyOrg/HandyWinGet-GUI

**Comment by Poopooracoocoo** [comment]
@ghost1372 you could ask the MSIX peeps for some help. i think they're open to suggestions too
